### PR TITLE
Added a PagedContent singleton builder

### PR DESCRIPTION
**Pull request by itzg**
# Resolves

Part of https://jira.rax.io/browse/SALUS-204

# What

Adds a helper method for building a `PagedContent` from a single value.

### CODE REVIEW

**Comment by jjbuchan** [comment]
I don't really get this.  Why would we be sending paged attributes for a single value?  Wouldn't it just return data for the single value rather than a list?

**Comment by itzg** [comment]
> I don't really get this. Why would we be sending paged attributes for a single value? Wouldn't it just return data for the single value rather than a list?

This is a GraphQL quirk. In order to overload the `monitors` and `resources` queries all overloaded methods must return the same data type...so a list or paged content thereof is the common return type.

**Comment by jjbuchan** [comment]
Oh right.  The internal service apis dont use this at all, just graphql?

**Comment by itzg** [comment]
@jjbuchan in case it helps, here's how the overloaded `monitors` looks in the schema docs:

image

**Pull request merged**
